"""Aggregate AuditVerdicts into per-rule summaries and render a markdown report."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone

from .schemas import (
    AuditReport,
    AuditVerdict,
    Deployment,
    Rule,
    RuleSummary,
)


def build_report(
    deployment: Deployment,
    rules: list[Rule],
    verdicts: list[AuditVerdict],
) -> AuditReport:
    by_rule: dict[str, list[AuditVerdict]] = defaultdict(list)
    for v in verdicts:
        by_rule[v.rule_id].append(v)

    summaries = []
    for r in rules:
        vs = by_rule.get(r.id, [])
        summaries.append(
            RuleSummary(
                rule=r,
                n_total=len(vs),
                n_output_aligned=sum(1 for v in vs if v.output_aligned),
                n_internal_aligned=sum(1 for v in vs if v.internal_aligned),
                n_divergent=sum(1 for v in vs if v.divergence),
                verdicts=vs,
            )
        )

    return AuditReport(
        deployment=deployment,
        generated_at=datetime.now(timezone.utc),
        summaries=summaries,
    )


def _bar(passed: int, total: int, width: int = 12) -> str:
    if total == 0:
        return "—"
    filled = round((passed / total) * width)
    return "█" * filled + "░" * (width - filled)


def render_markdown(report: AuditReport) -> str:
    lines: list[str] = []
    d = report.deployment
    lines.append(f"# Verbalize alignment audit: {d.name}\n")
    lines.append(f"_Generated {report.generated_at.isoformat(timespec='seconds')}_\n")
    lines.append(f"**Base model under audit:** `{d.base_model}`\n")

    total_runs = sum(s.n_total for s in report.summaries)
    total_out = sum(s.n_output_aligned for s in report.summaries)
    total_int = sum(s.n_internal_aligned for s in report.summaries)
    total_div = sum(s.n_divergent for s in report.summaries)

    lines.append("## Summary\n")
    lines.append(f"- Probes run: **{total_runs}**")
    lines.append(f"- Output-layer compliance: **{total_out}/{total_runs}** ({report.overall_pass_rate_output:.0%})")
    lines.append(
        f"- Residual-stream compliance: **{total_int}/{total_runs}** ({report.overall_pass_rate_internal:.0%})"
    )
    lines.append(f"- Divergent runs (output-compliant, internally non-compliant or vice versa): **{total_div}**\n")

    lines.append("## Per-rule results\n")
    lines.append("| Rule | Severity | Output aligned | Internal aligned | Divergent |")
    lines.append("|---|---|---|---|---|")
    for s in report.summaries:
        out_cell = f"{s.n_output_aligned}/{s.n_total} `{_bar(s.n_output_aligned, s.n_total)}`"
        int_cell = f"{s.n_internal_aligned}/{s.n_total} `{_bar(s.n_internal_aligned, s.n_total)}`"
        lines.append(f"| **{s.rule.name}** | {s.rule.severity} | {out_cell} | {int_cell} | {s.n_divergent} |")
    lines.append("")

    lines.append("## Detail\n")
    for s in report.summaries:
        lines.append(f"### {s.rule.name} (`{s.rule.id}`)\n")
        lines.append(f"_{s.rule.description.strip()}_\n")
        if not s.verdicts:
            lines.append("(no probes were run for this rule)\n")
            continue

        # Highlight divergent cases first (the load-bearing signal)
        divergent = [v for v in s.verdicts if v.divergence]
        clean = [v for v in s.verdicts if not v.divergence]

        if divergent:
            lines.append("**Divergent runs (the column black-box red-teaming cannot produce):**\n")
            for v in divergent:
                lines.append(f"- `{v.probe_id}`")
                lines.append(f"  - output_aligned: **{v.output_aligned}** — _{v.evidence_output}_")
                lines.append(f"  - internal_aligned: **{v.internal_aligned}** — _{v.evidence_internal}_")
                lines.append(f"  - rationale: {v.rationale}")
            lines.append("")

        if clean:
            lines.append(f"<details><summary>{len(clean)} non-divergent runs</summary>\n")
            for v in clean:
                status = "PASS" if v.output_aligned else "FAIL"
                lines.append(f"- `{v.probe_id}` — {status}: {v.rationale}")
            lines.append("\n</details>\n")

    lines.append("---")
    lines.append(
        "_Audit produced by `audit/` module. Probes generated by Claude with structured output, "
        "run through the live Verbalize stack, judged with separate output-only and "
        "thought-stream-only evidence requirements per [`audit/judge.py`](./judge.py)._"
    )
    return "\n".join(lines)
